// main.js - init(), window event listeners, handleRunBtn()

'use strict';

import { DEFAULTS } from './defaults.js';
import { computeSimulation } from './simulation.js';
import { computeWarnings } from './warnings.js';
import { drawBelt, drawErrorHaltOverlay } from './canvas.js';
import { updateMetrics, updateThermalUI, showRunSummary, setBinCount, flashBin, updateBinMatchState } from './metrics.js';
import { buildControls, onSlider, onSliderInput, setParam, setParamSlider, setInterrunGapSec, registerControlCallbacks } from './controls.js';
import { switchTab, addEvent, populateBrickTable, updateWarningsUI } from './tabs.js';
import { state, registerCallbacks, startSim, resetSim, setSpeed, runInstant } from './animation.js';
import { startReplay } from './replay.js';

// Initialize params from defaults
state.params = JSON.parse(JSON.stringify(DEFAULTS));
const params = state.params;

function setText(id, text) {
  const el = document.getElementById(id);
  if (el) el.textContent = text;
}

function updateWarnings() {
  const warnings = computeWarnings(params, state.simData);
  updateWarningsUI(warnings);
}

function doDrawBelt(ctx, W, H, simMs) {
  drawBelt(ctx, W, H, simMs, params, state.liveBinCounts, state.sceneState, state.animBricks, state.replayMode);
}

function doDrawErrorHaltOverlay(ctx, W, H, msg) {
  drawErrorHaltOverlay(ctx, W, H, msg);
}

// Register all callbacks into animation.js
registerCallbacks({
  updateWarnings,
  showRunSummary,
  updateThermalUI,
  setBinCount,
  flashBin,
  updateBinMatchState,
  drawBelt: doDrawBelt,
  drawErrorHaltOverlay: doDrawErrorHaltOverlay,
  addEvent,
  populateBrickTable,
  setText,
});

// Register callbacks into controls.js
registerControlCallbacks({
  updateMetrics,
  updateWarnings,
});

// Expose globals for inline HTML event handlers (generated by buildControls)
window._onSlider = (id, val) => onSlider(id, val, params);
window._onSliderInput = (id, val) => onSliderInput(id, val, params);
window._setParam = (id, val) => setParam(id, val, params);
window._setParamSlider = (id, rawVal, valElId, divisor, unit) => setParamSlider(id, rawVal, valElId, divisor, unit, params);
window._setInterrunGapSec = (sec) => setInterrunGapSec(sec, params);
window.switchTab = switchTab;
window.setSpeed = (s) => setSpeed(s);
window.runInstant = function() {
  runInstant(computeSimulation, params, updateWarnings, populateBrickTable);
};

window.handleRunBtn = function() {
  if (state.animRunning) {
    state.animPaused = !state.animPaused;
    document.getElementById('runBtn').textContent = state.animPaused ? 'Resume' : 'Pause';
    return;
  }
  startSim(computeSimulation, params, updateWarnings, populateBrickTable);
};

window.resetSim = function() {
  resetSim(params, doDrawBelt);
};

function resizeCanvas() {
  const canvas = document.getElementById('belt-canvas');
  const wrap = document.getElementById('belt-wrap');
  if (!canvas || !wrap) return;
  canvas.width = wrap.clientWidth;
  canvas.height = 240;
  if (!state.animRunning) {
    const ctx = canvas.getContext('2d');
    doDrawBelt(ctx, canvas.width, canvas.height, 0);
  }
}

function handleLoadCSV() {
  const input = document.createElement('input');
  input.type = 'file';
  input.accept = '.csv,text/csv,text/plain';
  input.onchange = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (ev) => {
      if (state.animRunning) {
        resetSim(params, doDrawBelt);
      }
      startReplay(ev.target.result, params, updateWarnings, populateBrickTable);
    };
    reader.readAsText(file);
  };
  input.click();
}

function init() {
  buildControls(params);
  updateMetrics();
  updateWarnings();
  resizeCanvas();

  window.addEventListener('resize', resizeCanvas);

  const loadCsvBtn = document.getElementById('loadCsvBtn');
  if (loadCsvBtn) loadCsvBtn.addEventListener('click', handleLoadCSV);
}

init();
