[platformio]
default_envs = esp32dev
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    madhephaestus/ESP32Servo @ ^0.13.0
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    Preferences
build_flags =
    -DCORE_DEBUG_LEVEL=0
build_src_filter =
    -<*>
    +<tsa_sorter/>
    -<tools/>
